sudo: required
services:
  - docker

before_install:
  - docker build -t ds/web-api .

script:
  - docker run ds/web-api mvn test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ds/web-api

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "research-app"
  env: "ResearchApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-103680327272"
  bucket_path: "research-app"
  on:
    branch: master
  access_key_id: $aws_access_key
  secret_access_key:
    secure: $aws_secret_key
