version: '3'
services:
  db:
    build:
      context: './deploy/postgres'
      dockerfile: Dockerfile
    container_name: db
    ports:
      - "5432:5432"
  web-app:
    working_dir: '/app'
    build: .
    container_name: web-app
    depends_on:
      - db
    ports:
      - "8080:8080"
